apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-deployment
  labels:
    app: pyt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyt-app
  template:
    metadata:
      labels:
        app: pyt-app
    spec:
      containers:
      - name: python-app
        image: livevil8/python-sample:v1
        #This is a part of ConfigMap
        #env:
        #- name: DB-PORT
         # valueFrom: 
          #  configMapKeyRef:
           #   name: test-cm
            #  key: db-port
        volume Mounts:
          - name: db-connection
            mount: /opt
        ports:
        - containerPort: 8000
      # instead of env we can use volumes
      volumes:
        - name: db-connection
          configMap:
            name: test-cm
